"""initial tables

Revision ID: 5fd5c41a9dbe
Revises: c82f7a3d91aa
Create Date: 2026-10-02 20:13:52.830420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fd5c41a9dbe'
down_revision: Union[str, Sequence[str], None] = 'c82f7a3d91aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'back',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_index(op.f('ix_decks_id'), 'decks', ['id'], unique=False)
    op.alter_column('review_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('review_history', 'interval',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review_history', 'ease_factor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_review_history_id'), 'review_history', ['id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_review_history_id'), table_name='review_history')
    op.alter_column('review_history', 'ease_factor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review_history', 'interval',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_decks_id'), table_name='decks')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.alter_column('cards', 'back',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
